from enum import Enum

VERSION_BYTE_SIZE = 1
CLIENT_ID_BYTE_SIZE = 16
REQUEST_CODE_BYTE_SIZE = 2
RESPONSE_CODE_BYTE_SIZE = 2
PAYLOAD_SIZE_BYTE_SIZE = 4
USER_NAME_BYTE_SIZE = 255
PUBLIC_KEY_BYTE_SIZE = 160
MESSAGE_TYPE_BYTE_SIZE = 1
CONTENT_SIZE_BYTE_SIZE = 4
MESSAGE_ID_BYTE_SIZE = 4

SERVER_INFO_FILE_NAME = "myport.info"
MIN_VALID_PORT_NUMBER = 1024
MAX_VALID_PORT_NUMBER = 65535


BUFFER_PARTITION_SIZE = 1024
MAX_PULLED_MESSAGES_DATA = 0xFFFFFFFF


class RequestCode(Enum):
    REGISTER = 1100
    LIST_CLIENTS = 1101
    GET_PUBLIC_KEY = 1102
    SEND_MESSAGE = 1103
    PULL_MESSAGES = 1104


class MessageType(Enum):
    REQUEST_SYMMETRIC_KEY = 0
    SEND_SYMMETRIC_KEY = 1
    SEND_TEXT_MESSAGE = 2
    SEND_FILE = 3


class ResponseCode(Enum):
    REGISTER_SUCCESS = 2100
    LIST_CLIENTS_SUCCESS = 2101
    PUBLIC_KEY_SUCCESS = 2102
    MESSAGE_SENT_SUCCESS = 2103
    MESSAGES_PULLED_SUCCESS = 2104
    GENERAL_SERVER_ERROR = 9000


class RequestParseStatus(Enum):
    UNDONE = "UNDONE"
    DONE = "DONE"
